### ISSUE TITLE
Vogen From method not recognized under Framework 4.8

### ISSUE THREAD

**Issue by squideyes** [SteveDunn/Vogen#111]
### Describe the bug

When I create a project using Framework 4.8 (see "Steps To Reproduce"), I get a 'CustomerId' does not contain a definition for 'From' error message.

### Steps to reproduce

(1) Create a "Console App (.NET Framework), using .NET Framework 4.8
(2) Add a "Vogen" NuGet ( I tried 1.0.18, 1.0.17 and 1.0.15)
(3) Replace the code in Program.cs with the following:

using Vogen;

namespace ConsoleApp1
{
    [ValueObject]
    public partial struct CustomerId
    {
        // optional
        private static Validation Validate(int value) => value > 0
            ? Validation.Ok
            : Validation.Invalid("Customer IDs must be a positive number.");
    }

    internal class Program
    {
        static void Main(string[] args)
        {
            CustomerId customerId = CustomerId.From(123);
        }
    }
}

### Expected behaviour

The From method would be recognized, allowing the code to be compiled and used as expected

**Comment by SteveDunn** [comment]
Hi @squideyes - many thanks for the bug report. The problem looks like it's due to missing a reference to `System.Text.Json` (STJ).

Vogen generates code so that value objects can be serialised in STJ.  You have 2 choices:

1. Added a reference to the STJ nuget package
2. If you don't want a dependency on STJ, add a `VogenDefaults` attribute to your assembly, like so:
```diff
using Vogen;

+ [assembly: VogenDefaults(conversions: Conversions.TypeConverter)]

namespace ConsoleApp1
{
    [ValueObject]
    public partial struct CustomerId
    {
// optional
        private static Validation Validate(int value) => value > 0
            ? Validation.Ok
            : Validation.Invalid("Customer IDs must be a positive number.");
    }
    
    internal class Program
    {
        static void Main(string[] args)
        {
            CustomerId customerId = CustomerId.From(123);
        }
    }
}
```

It's not the best experience for a new user of the library, so I appreciate you taking the time to report the bug.

I'll try to make this scenario more obvious so users will know what to do.

Thanks again!

**Comment by squideyes** [comment]
Hi!  Thanks for the quick and illuminating reply.  Unfortunately, neither suggestion worked.  (See [ConsoleApp1.zip](https://github.com/SteveDunn/Vogen/files/8475509/ConsoleApp1.zip) for an example of the problem)

**Comment by SteveDunn** [comment]
Oh, that's not good. Thanks for providing the repo project. I've been looking at the problem and have updated the documentation. Because you're not use the 'SDK Style' project, source generators are not run when referenced from `packages.config`. I've [updated the readme](https://github.com/SteveDunn/Vogen#what-versions-of-net-are-supported) with a workaround and will look at a better way of installation for .NET Framework.

**Comment by SteveDunn** [comment]
Relevant thread: https://discord.com/channels/732297728826277939/735233259763400715/963539625186590772

**Comment by SteveDunn** [comment]
@squideyes - sorry for the very slow follow-up. Thank you for the kind words re. this work, much appreciated. Did the recommendations in the README help at all?

**Comment by squideyes** [comment]
The readme did help, so thanks.  BTW, I got to show Vogen to the Philly.NET User Group a few months ago and it was quite well received.  Thanks...

**Comment by SteveDunn** [comment]
Excellent, thank you for spreading the word!

**Comment by arteny** [comment]
Used all recommendations from doc for .net framework, but it doesn't work for me for .net framework 4.7.1
```
error CS0117: 'TabName' does not contain a definition for 'From'
```

**Comment by SteveDunn** [comment]
@arteny - I just skimmed through this thread, not bothering to read the comments above yours. I created a 4.7.1 app, and Vogen wasn't recognised. I'd completely forgot about the special instructions for .NET Framework, but once I followed them, it _mostly_ worked. The only thing I had to do, in addition to the other things in the readme, was add the following in the consuming `.csproj`

```xml
  <PropertyGroup>
    <RuntimeIdentifiers>win</RuntimeIdentifiers>
  </PropertyGroup>

```

I've attached the project here. Let me know if this helps.

[ConsoleApp17.zip](https://github.com/SteveDunn/Vogen/files/15171249/ConsoleApp17.zip)

**Comment by SteveDunn** [comment]
@arteny - are you still having issues, or should I close this?

**Comment by squideyes** [comment]
Please close it.  Thanks….

**Comment by arteny** [comment]
> @arteny - are you still having issues, or should I close this?
yes, close please
