### ISSUE TITLE
Ignore  ‘CS1591 missing XML comments'

### ISSUE THREAD

**Issue by SteveDunn** [SteveDunn/Vogen#209]
### Describe the feature

For projects that have mandatory XML comments turned on, the compiler doesn't seem to recognise generated files and still produced CS1591.

Check before implementing, that disabling CS1591 in the generated file doesn't disable the requirements for triple-slass comments in the users partial file.

**Comment by Herdo** [comment]
@SteveDunn Alternative: we could generate the comments?

**Comment by SteveDunn** [comment]
> @SteveDunn Alternative: we could generate the comments?

@Herdo - yes, there are some existing public methods that are commented, plus I've  added a couple more, however it's tricky to comment the type itself, as a) the user might've commented it already, and b) if they haven't, what should the comment be...

**Comment by Herdo** [comment]
> it's tricky to comment the type itself, as a) the user might've commented it already, and b) if they haven't, what should the comment be...

> For projects that have mandatory XML comments turned on

@SteveDunn It's the developers choice to have the XML comments mandatory rather than optional, right?
If they do opt in into having mandatory comments, they have to comment their public types as well. Do on a class / record / struct level, they choose that comments are required and therefore have to provide them on their partial file.

So it always has to be case a) and never b), as Vogen only takes care of members (and interface inheritance), not the type itself.

**Comment by SteveDunn** [comment]
@Herdo , yes, for the members of the type, but that's only `ToString` (currently). `ToString` is now commented in the generated code (if the user hasn't provided their own `ToString` method).

I've add a pragma to disable the warning and also commented `Value` and `ToString`
