### ISSUE TITLE
Struct ValueObject does not work with LinqToDB

### ISSUE THREAD

**Issue by timbze** [SteveDunn/Vogen#255]
I am not sure why, or even if it should, but it seems that `LinqToDB` does not listen to converters at all for structs. If I change the value object to `record` then it works.

Possibly the issue should be documented, or even add an analyzer to warn about struct usage with LinqToDb ValueConverter. Or maybe LinqToDB could/should fix it, but I don't know well enough how it works for them...

```csharp
// this type in POCO fails
[ValueObject(typeof(string), conversions:Conversions.LinqToDbValueConverter)]
public partial struct DataId {}

// this type works EDIT not working after all
[ValueObject(typeof(string), conversions:Conversions.LinqToDbValueConverter)]
public partial record DataId {}
```

The error I get for `struct`:
```
Unhandled exception. System.NotSupportedException: The CLR type DataId isn't natively supported by Npgsql or your PostgreSQL. To use it with a PostgreSQL composite you need to specify DataTypeName or to map it, please refer to the documentation.
```

**EDIT**
Looks like `record` type is not working after all, has the same error. I guess there needs to be some mapping with LinqToDB or Npgsql my dataProvider

**Comment by timbze** [comment]
Well, looks like I didn't know what the ValueConverter is for, this works for struct and record (in POCO):
```csharp
[Column] // << works without Column attribute for struct, but is needed for record
[ValueConverter(ConverterType = typeof(DataId.LinqToDbValueConverter))]
public DataId DataId { get; set; }
```

**Comment by SteveDunn** [comment]
Hi @timbze - glad you've got it fixed and working.

Personally, I stopped trying to use Value Objects anywhere outside the domain as it was more trouble than it was worth. I found that the domain concepts for these objects changed over time, but that it was impossible (or just not worth the time and trouble) to keep the logic (validation) and everything that's ever been persisted in check.

**Comment by jeffward01** [comment]
> Hi @timbze - glad you've got it fixed and working.
> 
> Personally, I stopped trying to use Value Objects anywhere outside the domain as it was more trouble than it was worth. I found that the domain concepts for these objects changed over time, but that it was impossible (or just not worth the time and trouble) to keep the logic (validation) and everything that's ever been persisted in check.

When it works its nice, but I find myself fighting the EfCore code and struggling.

I read on a efcore issue that one guy simply had to restart his computer because of some caching related issue (this was for StronglyTypedIds by Andrew Locke, similar library).

It can absolutely be a pain. I'd save more time if I just copied you and only used ValueObjects like this in the domain, it would save so much time. Im about 15 minutes away from this choice.

Thanks for being honest, so many times, you go on the `efcore` issues or `insert-other-library-of`choice`, and they make it look so easy, but in reality, there are so many factors, especially in source generators.

I am a contributor here: https://github.com/Testura/Testura.Code and usually build 'out-of-process' code generators, console apps and such.  Not as elegant as Source Generators, but they just work.

Another annoying bit about Source Generators is this bug (this is Rider btw):

![image](https://user-images.githubusercontent.com/12589359/211448825-cc29bbb2-2154-44ef-88e9-993a6820bbf3.png)


The code compiles 100% fine, but Rider marks this as red.  VS does this too I think.  Its pretty common.  The solution to this.... as I understand it:

* Close VS (Rider) and re-open it.
   * smacks forehead, this happens every few builds, so its very often.

Anyways, sorry for rant and de-railing topic.

**Comment by SteveDunn** [comment]
@jeffward01 - yes, I see that too. I really need to raise a ticket with Jetbrains to get it looked at as it's very annoying (that, and the fact that Rider doesn't show the proper debug hints)

**Comment by jeffward01** [comment]
> @jeffward01 - yes, I see that too. I really need to raise a ticket with Jetbrains to get it looked at as it's very annoying (that, and the fact that Rider doesn't show the proper debug hints)

It's been raised several times with JetBrains, and they keep closing the ticket.  See: 

* [RIDER-75429](https://youtrack.jetbrains.com/issue/RIDER-75429)
* [RIDER-74077](https://youtrack.jetbrains.com/issue/RIDER-74077)
* [RIDER-65552](https://youtrack.jetbrains.com/issue/RIDER-65552) <-- this is the main one

I opened a new ticket a few months ago here: https://youtrack.jetbrains.com/issue/RIDER-85940/Rider-often-does-not-detect-source-generated-code-and-marks-it-as-missing-references

They need me to supply some debugging data, I just saw their query to me on this a few days ago, and have not had the opportunity to do so.
