### ISSUE TITLE
[Question] `TimeOnly` and `DateOnly` are these converion types implemented? If so, would a PR be accepted?

### ISSUE THREAD

**Issue by jeffward01** [SteveDunn/Vogen#310]
### Describe the feature

Hello!

Again thank you for the library and your aweomse work on it! I use it daily in JB Rider as many others do!

I was wondering if `DateOnly` and `TimeOnly` are implemented as conversion types? 
 _I know that these are newly introduced as `net6.0`, or was it `net5.0` (I think it was `net5.0`, i have to check) so that some target framework `#if net5.0` type logic would need to be used_

I saw the list of supported conversion types [here](https://github.com/SteveDunn/Vogen#what-primitive-types-are-supported) - and did not see `DateOnly` / `TimeOnly`.

I also reviewed your code quickly and could not find any references either.

## Questions
I wanted to ask for a few reasons:

1.) Maybe there is something im missing how you can convert `DateTime` to `TimeOnly` or `DateOnly` and i am not aware that `Vogen` implements this.

2.) To ask, if find some time to submit a PR, is there anything I should make sure I implement for this? Are there any 'gotchas' with deployment and assembly targets regarding adding these newer types?

## Proposal to add

I understand that you allow custom converters to be implemented, that is great. I think it would also be worth while to target `DateOnly` or `TimeOnly` for the same reasons that the dotnet team added `DateOnly` and `TimeOnly`.

My apologies if this has already been asked or implemented, I checked the issues and did not see this referenced.

Thanks again!

**Comment by SteveDunn** [comment]
Hi @jeffward01 - thanks for the feedback and the encouragement. It's lovely to hear of people using Vogen!

They're not implemented yet, but I think they should be. Here are the types currently implemented:

![image](https://user-images.githubusercontent.com/263416/209425670-eb0e5b19-767b-4ca2-851f-000705bb134b.png)

For each new type, we also need to add templates for conversion to/from the various persistence mechanism, such as Dapper/EFCore/*.Json etc. (as shown in the screenshot above)

Re. your questions:
1. There isn't anything _directly_ in Vogen (yet), but you can convert the _value_
2. A PR would be great, although there are gotchas. Source generators and analyzers are a pain to test. There's also quite a few places in the code that need to know the supported primitives, so it's not a light touch change. 

I will start work on adding these, but if you could lend a hand, then that would be great. The change will require tests for Dapper/EF Core/LinkqToDb/Newtonsoft.Json/System.Text.Json, and TypeConverters. It shouldn't be too arduous though as I would imagine a lot of similarity to the template for `DateTime` here: https://github.com/SteveDunn/Vogen/tree/main/src/Vogen/Templates/DateTime

The samples are here: https://github.com/SteveDunn/Vogen/tree/main/samples/Vogen.Examples/SerializationAndConversion, so we'd need to add some for `DateOnly` and `TimeOnly`.

I think a good plan of approach would be for me to initially make the changes so that the source generator is aware of the new types, and then, if you've got time, fill in the blanks for the templates.

Thanks again for the feedback!

**Comment by jeffward01** [comment]
Happy New Years!

Sorry for the delay in response, I have been swamped on this project I have been working on and not able to get around to this, I have been thinking about this for a while.  

I'd love to write the unit tests, but it looks like you beat me to it! I am sorry about that! 

I hope you had a good Holiday season and happy new years!

Jeff

**Comment by SteveDunn** [comment]
Hi @jeffward01 - Happy New Year! No worries at all. Let me know if there's any issues with it.
