### ISSUE TITLE
UnderlyingType on ValueObjectAttribute

### ISSUE THREAD

**Issue by dibble-james** [SteveDunn/Vogen#356]
### Describe the feature

All the properties on the `ValueObjectAttribute` appear to have been commented out at some point.  If this wasn't deliberate could they be reinstated? `UnderlyingType` in particular would be quite useful for creating custom converters that aren't currently supported (currently working with both GraphQL and MongoDb)

**Comment by SteveDunn** [comment]
Hi @dibble-james - the original intention of the attributes was to purely control source generation at compile time. However, I can't see any major downsides in actually storing the underlying type. I'm guessing that, for your case, a `.Value.GetType()` isn't sufficient because `Value` will throw if the instance is uninitialized?

**Comment by dibble-james** [comment]
I hadn't thought of doing `.Value.GetType`, but yes, I'd have to give it some value and validation on most types would stop you using `default(T)` to initialise an instance.

Yeah I could see how that could be confusing having only one of the fields exposed even if they make no sense at runtime!

Creating a child attribute type is also a good shout. Personally that would work for me as an incremental step whilst I have a go at SG templates for the scenarios I've got. Avoiding reflection is one of the benefits of SG after all!

Do with the PR as you will, no hard feelings :)

**Comment by dibble-james** [comment]
I ended up with something like this:

```csharp
```

**Comment by SteveDunn** [comment]
Thanks for the info @dibble-james . I'll add this to the documentation.
