### ISSUE TITLE
Consider adding an optional `Code` to validation exceptions

### ISSUE THREAD

**Issue by glen-84** [SteveDunn/Vogen#374]
### Describe the feature

```cs
throw new ValueObjectValidationException("message", "code");

Validation.Invalid("message", "code")
```

Codes are shorter, updated less frequently, and easier to assert on.

**Comment by SteveDunn** [comment]
Thanks for the idea @glen-84 - sorry it's been a while responding.
I think if users want customized exceptions, then they'd have much more flexibility by just throwing their own exceptions, e.g. instead of returning `Validation.Invalid("the message")`, you could just `throw new DomainValidationException("the message", "the error code")`.

I realise that this isn't mentioned in the readme, but I'm open to contributions to the docs! ;) 

Thanks again for the idea!

**Comment by glen-84** [comment]
I didn't even think of that! Thanks a lot for the reply.
