### ISSUE TITLE
Why implicit comparison is allowed?

### ISSUE THREAD

**Issue by arteny** [SteveDunn/Vogen#561]
### Describe the bug

Not sure that it is correct behaior for ValueObject as strong typed value
```
			_ = EventId.From("123456789*") == "ddd";
```
There is no any compilation error.

### Steps to reproduce

Compile.

### Expected behaviour

Compilation error.

**Comment by arteny** [comment]
And I meat ths issue in real usage now. I thing it should be most priority issue to fix, else it break all concepts of ValueObject.
When I using this code  
```
await db.Exposures.Where(x => x.Market.Id == market.Id).ExecuteDeleteAsync();
```
it is no any errors or warnings during the compilation, but in execution time i get the error:
```
System.InvalidCastException: Invalid cast from 'System.String' to 'Domain.Enums.MarketId'
```
market.Id is string here, so to get it working i need to change it to `MarketId.From(market.Id)`, but I expect to know it before I am running my program
MarketId type has a following definition:
```
[ValueObject<string>(conversions: Conversions.EfCoreValueConverter | Conversions.Default)]
```

**Comment by SteveDunn** [comment]
Hi @arteny , this is correct behaviour. Or at least it's behaviour that has been there since inception.

Vogen generates the following equality methods for all underlying types. For a `string` it's

```
        public static bool operator ==(EventId left, string right) => Equals(left.Value, right);
        public static bool operator !=(EventId left, string right) => !Equals(left.Value, right);
```

> As for me, it breaks all concepts of ValueObject

Two of the main concepts of a Value Object are:
* it's difficult to create an invalid instance 
* they help 'strongly type' primitives

For the latter, encapsulation isn't broken; `Equals(this, string other)` doesn't allow you to access `this` if it isn't valid, and the comparison to the underlying `string` doesn't create any other value object.

I think that EF is taking your `where` expression and rewriting it in such a way that the Equals is being ignored and a direct cast is used instead. 
Looking online reveals lots of issues related to comparisons in expressions (most are related to casing of the string).

There are a few additional things that you need to do before using Vogen types with EF. These are described in this [How To article](https://stevedunn.github.io/Vogen/efcoreintegrationhowto.html).  I hope this solves your problem. If you could let me have some feedback on that article (or better still, [modify it](https://github.com/SteveDunn/Vogen/blob/main/docs/site/Writerside/topics/reference/EfCoreIntegrationHowTo.md) if there's something missing/incorrect/confusing), that'd be great.

**Comment by SteveDunn** [comment]
Closing this as I'm confident that the additional setup shown in [the documentation](https://github.com/SteveDunn/Vogen/blob/main/docs/site/Writerside/topics/reference/EfCoreIntegrationHowTo.md) will solve this issue, but please let me know if it doesn't.
