### ISSUE TITLE
Vogen OpenApi Mapping Issue

### ISSUE THREAD

**Issue by Aragas** [SteveDunn/Vogen#608]
When using `OpenApiSchemaCustomizations.GenerateSwashbuckleMappingExtensionMethod` and the underlying type is `Guid` or `byte` (most likely other non-`int `types) it creates a mapping to an object, not the correctly expected type.  
It's not a critical issue for me, since I use `OpenApiSchemaCustomizations.GenerateSwashbuckleSchemaFilter`, but most likely it will be reported later

**Comment by SteveDunn** [comment]
Thanks for reporting! I'll look at that shortly.

**Comment by SteveDunn** [comment]
Ah, this is because of this method and the limited types in json schemas:

```
    private static string MapUnderlyingTypeToJsonSchema(string primitiveType)
    {
        string jsonType = primitiveType switch
        {
            "System.Int32" => "integer",
            "System.Single" => "number",
            "System.Decimal" => "number",
            "System.Double" => "number",
            "System.String" => "string",
            "System.Boolean" => "boolean",
            _ => "object"
        };

        return jsonType;
    }
```

I've modified this so that if the underlying type is `IParsable`, then it treats it as a `string`.

Added an example to web app in the `Consumers` project. Here's a new endpoint that takes a Guid:

![image](https://github.com/SteveDunn/Vogen/assets/263416/88447068-c3bf-4d8c-b1b8-5f8d0a56ef10)
