### ISSUE TITLE
Add support for making value objects easier to use in Marten

### ISSUE THREAD

**Issue by SteveDunn** [SteveDunn/Vogen#609]
### Describe the feature

It is difficult to use value objects generated with Vogen in [Marten](https://martendb.io/). While value objects are best used in domain code, they are often used in infrastructure code.
The issues are highlighted in this thread: https://x.com/jeremydmiller/status/1796720636460745213

**Comment by ChristopherLenz** [comment]
@SteveDunn 
I have been using Marten for a while and today I found this project. Up until now we have always implemented our primitives ourselves and I am really impressed with this solution here.

Now I am wondering what needs to be done so that I can use it in the domain code? You wrote that it is difficult?! So there seems to be a solution?

**Comment by SteveDunn** [comment]
Hi @ChristopherLenz - thanks for the feedback! Apparently, in recent versions of Marten now have support for Vogen. It was implemented in this PR: https://github.com/JasperFx/marten/pull/3268/files
I've just found some conversations in their Discord channel that might steer you in the right direction: https://discord.com/channels/1074998995086225460/1074999076896112661/1258170623780196457

Hope that helps. Let me know how you get on, as I think this issue can now be closed.
