### ISSUE TITLE
Conflict between `CastOperator.Implicit` and `StaticAbstractsGeneration.MostCommon`

### ISSUE THREAD

**Issue by ValeriyGourov** [SteveDunn/Vogen#720]
### Describe the bug

When we use implicit primitive casting and try to generate an `IVogen` interface, we get an error like this one:
> Error CS0535 : 'ToDoItemId' does not implement interface member "IVogen<ToDoItemId, int>.explicit operator int(ToDoItemId)"

### Steps to reproduce

Add the following code to an empty project and compile.
```csharp
[assembly: VogenDefaults(
	toPrimitiveCasting: CastOperator.Implicit,
	staticAbstractsGeneration: StaticAbstractsGeneration.MostCommon)]

[ValueObject<int>]
public readonly partial record struct ToDoItemId;
```

### Expected behaviour

We should be able to provide implicit cast operator with `IVogen` interface.

**Comment by SteveDunn** [comment]
Thanks for the bug report @ValeriyGourov .

The issue here is that Vogen is generating *both* implicit and explicit operators, which isn't allowed in C#.

The defaults for `VogenDefaults` are `explicit` casts to and from the primitive. You're specifying an `implicit` cast to the primitive _and also_ an `explicit` cast to the primitive by using `StaticAbstractsGeneration.MostCommon`.

To get this work, use:

```c#
                     using static Vogen.StaticAbstractsGeneration;
                     
                     [assembly: VogenDefaults(
                         toPrimitiveCasting: CastOperator.Implicit,
                         staticAbstractsGeneration: ValueObjectsDeriveFromTheInterface |
                                                    EqualsOperators |
                                                    ExplicitCastFromPrimitive |
                                                    ImplicitCastToPrimitive |
                                                    FactoryMethods)]
```

The compilation errors are not great though, so I've added a check to spot both types of cast and it writes:
```
error VOG036: ToDoItemId should have either an explicit or implicit cast to or from the wrapper or primitive, 
but not both. Check that the global config isn't specifying a conflicting casting operator. 
Check 'toPrimitiveCasting', 'fromPrimitiveCasting', and 'staticAbstractsGeneration'. 'staticAbstractGeneration' 
defaults to explicit casting, so if you change the default, you need to change it here too. See issue 720
(https://github.com/SteveDunn/Vogen/issues/720) for more information.
```

This will be in the next beta release.

Thanks again for the report, let me know if there's anything else I can clarify.

**Comment by ValeriyGourov** [comment]
@SteveDunn Thanks! 😊
